name: "homelab"
services:

  binfmt:
    image: tonistiigi/binfmt
    privileged: true
    command: --install amd64

  homelab:
    container_name: "homelab"
    build:
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - /opt/homelab:/opt/homelab
      - share:/usr/local/share
      - user:/root
    networks:
      - default
      - proxy

volumes:
  share:
  user:

networks:
  default:
    driver: bridge
  proxy:
    external: true